schema_version = "1.0.0"

id = "QP_Tools"
version = "2.2.2"
name = "QP_Tools"
tagline = "A set of scripts I use to make life easier"

maintainer = "Quentin Pointillart <quentin.pointillart@gmail.com>"

# Supported types: "add-on", "theme"
type = "add-on"

# # Optional: tag list defined by Blender and server, see:
# # https://docs.blender.org/manual/en/dev/advanced/extensions/tags.html
tags = ["Assets", "Library"]

blender_version_min = "4.2.0"


# License conforming to https://spdx.org/licenses/ (use "SPDX: prefix)
# https://docs.blender.org/manual/en/dev/advanced/extensions/licenses.html
license = [
  "SPDX:GPL-3.0-or-later",
]
